### ISSUE TITLE
Failed to build bundle due to errors on a clean React Native project

### ISSUE THREAD

**Issue by dule1322** [callstack/repack#72] opened 2021-08-19 12:29 UTC
## Environment

MacBook Pro 16 2019
`npx -v` = 7.5.3
XCode = 12.4
cocoapods = 1.10.1
Simulator = iPhone 12 Pro

## Description

I set up a react native project by using the `npx react-native init AwesomeProject` command, and after following the https://github.com/callstack/repack Installation & Setup section guide when I run the `npx react-native webpack-start` and when the application is started and connected to the server, bundling fails with the following error:

ℹ [12:25:10.889Z][DevServerProxy] Server listening at http://[::]:8081 
ℹ [12:27:31.506Z][DevServerProxy] Starting compiler worker { platform: 'ios', port: 49682 } 
ℹ [12:27:31.568Z][DevServerProxy] Hermes device connected { deviceId: 0 } 
ℹ [12:27:32.748Z][DevServer@ios] Server listening at http://127.0.0.1:49682 
ℹ [12:27:32.786Z][webpack-dev-middleware] wait until bundle finished: /index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AwesomeProject 
✖ [12:27:49.611Z][LoggerPlugin] Failed to build bundle due to errors 
✖ [12:27:49.611Z][LoggerPlugin] Error in "./node_modules/react-native/Libraries/Utilities/HMRClient.js": Module not found: Error: Can't resolve './getDevServerLocation' in '/Users/duskomirkovic/Documents/Projects/AwesomeProject/node_modules/react-native/Libraries/Utilities' 
⠦ Running: (ios)  100% 

## Reproducible Demo

1. Ran `npx react-native init AwesomeProject`
2. Ran `cd AwesomeProject`
3. Ran `yarn add -D webpack terser-webpack-plugin babel-loader @callstack/repack`
4. Created `react-native.config.js` with content specified here: https://github.com/callstack/repack
5. Created `webpack.config.js` with content from here: https://github.com/callstack/repack/blob/main/templates/webpack.config.js
6. Configured XCode build phase `Bundle React Native code and images` to match the one provided in the Installaton & Setup section here: https://github.com/callstack/repack
7. Ran `cd ios`
8. Ran `pod install`
9. Ran `cd ..`
10. Ran `npx react-native webpack-start`
11. Ran `npx react-native run-ios`

**Comment by zamotany** [comment] 2021-08-23 08:00
This is caused by braking change in Webpack 5.49.0 tracked here: #63 
For now, please downgrade Webpack to 5.48.0.

**Comment by zamotany** [comment] 2021-09-03 15:27
This problem was addressed in `@callstack/repack@2.0.0` - please update to this version.

**Closed by zamotany** 2021-09-03 15:27 UTC
Labels: duplicate
