### ISSUE TITLE
Unhandled error in Webpack Compiler when doing `rpm run ios`

### ISSUE THREAD

**Issue by thomasreiser** [callstack/repack#488] opened 2024-01-11 10:24 UTC
## Environment

Repack 3.7.0
React 18.2.0
React Native 0.73.2

## Description

Host server was started with `npx react-native webpack-start`. When I then run iOS with `npx react-native run-ios --no-packager` the app fails during bundling (at 99%):

<img width="396" alt="iOS error" src="https://github.com/callstack/repack/assets/170543/f9f77f37-119e-4797-97a0-ce288325349d">

The error in the host:

```
thomas@D1W0M599PT shell % npx react-native webpack-start          
(node:62856) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
ℹ [10:12:02.573Z][DevServer] Server listening at http://[::1]:8081 
ℹ [10:19:18.380Z][DevServer] GET 200 /status request completed { responseTime: 1.1502500008791685 } 
ℹ [10:19:18.434Z][DevServer] GET 200 /status request completed { responseTime: 0.3165000006556511 } 
ℹ [10:19:18.442Z][DevServer] Hermes device connected { deviceId: 0 } 
ℹ [10:19:19.988Z][WebpackCompilerWorker] {
  bundleFilename: '',
  context: '/Users/thomas/Documents/Private/shell,
  reactNativePath: '/Users/thomas/Documents/Private/shell/node_modules/react-native',
  mode: 'development',
  platform: 'ios',
  devServer: { port: 8081, host: '', https: undefined, hmr: true }
} 
⇢ [10:19:22.148Z][LoggerPlugin] Compiling ios: 3% setup (watch run) 
⇢ [10:19:22.798Z][LoggerPlugin] Compiling ios: 10% building (0/6 entries 6/6 dependencies 0/6 modules) 
⇢ [10:19:24.954Z][LoggerPlugin] Compiling ios: 10% building (0/6 entries 6/7 dependencies 0/6 modules) 
⇢ [10:19:26.843Z][LoggerPlugin] Compiling ios: 37% building (3/6 entries 359/500 dependencies 16/183 modules) 
⇢ [10:19:28.564Z][LoggerPlugin] Compiling ios: 46% building (4/6 entries 1185/1288 dependencies 100/328 modules) 
⇢ [10:19:31.477Z][LoggerPlugin] Compiling ios: 46% building (4/6 entries 2000/2080 dependencies 321/453 modules) 
⇢ [10:19:33.432Z][LoggerPlugin] Compiling ios: 46% building (4/6 entries 2157/2200 dependencies 341/479 modules) 
⇢ [10:19:34.635Z][LoggerPlugin] Compiling ios: 51% building (12/16 entries 2655/2659 dependencies 554/558 modules) 
node:internal/event_target:1096
  process.nextTick(() => { throw err; });
                           ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({})
    at Compiler.emit (node:events:508:17)
    at Worker.<anonymous> (/Users/thomas/Documents/Private/shell/node_modules/@callstack/repack/dist/webpack/Compiler.js:110:14)
    at Worker.emit (node:events:519:28)
    at MessagePort.<anonymous> (node:internal/worker:263:53)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:822:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'ERR_UNHANDLED_ERROR',
  context: {}
}

Node.js v21.4.0
```

The error can also be reproduced without the iOS simulator by requesting `http://localhost:8081/index.bundle?platform=ios&dev=true&lazy=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.easi`.

This is also not a federation issue as it also occurs when I try to startup a standalone app.

Is there a way to debug this or to get more infos about **what** failed?

**Comment by jfgaudreault-p** [comment] 2024-02-09 21:20
I am also getting the same error message issue when trying to run the host app of the [repack-examples](https://github.com/callstack/repack-examples/tree/main)
/module-federation project.

I am on linux and running the Android app, and the Bundling inside the app goes up to 98% then I get this error.
```
yarn start:host
ℹ [21:12:55.796Z][DevServer] Server listening at http://127.0.0.1:8081 
ℹ [21:13:06.816Z][DevServer] Hermes device connected { deviceId: 0 } 
ℹ [21:13:06.853Z][DevServer] GET 200 /status request completed { responseTime: 2.2725499998778105 } 
ℹ [21:13:07.005Z][WebpackCompilerWorker] {
  bundleFilename: '',
  context: '/home/user/repack-examples/module-federation/host',
  reactNativePath: '/home/user/repack-examples/module-federation/host/node_modules/react-native',
  mode: 'development',
  platform: 'android',
  devServer: { port: 8081, host: '', https: undefined, hmr: true }
} 
ℹ [21:13:07.208Z][DevServer] Successfully run: /home/user/Android/Sdk/platform-tools/adb reverse tcp:8081 tcp:8081 
⇢ [21:13:07.200Z][LoggerPlugin] Compiling android: 3% setup (watch run) 
⇢ [21:13:08.413Z][LoggerPlugin] Compiling android: 28% building (3/6 entries 100/300 dependencies 9/71 modules) 
⇢ [21:13:10.643Z][LoggerPlugin] Compiling android: 46% building (4/6 entries 1197/1265 dependencies 94/335 modules) 
⇢ [21:13:13.763Z][LoggerPlugin] Compiling android: 46% building (4/6 entries 1900/1989 dependencies 273/425 modules) 
⇢ [21:13:15.444Z][LoggerPlugin] Compiling android: 62% building (24/25 entries 2501/2502 dependencies 537/538 modules) 
/home/user/repack-examples/module-federation/host/node_modules/metro-hermes-compiler/src/emhermesc.js:77
          throw ex;
          ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({})
    at Compiler.emit (node:events:508:17)
    at Worker.<anonymous> (/home/user/repack-examples/module-federation/host/node_modules/@callstack/repack/dist/webpack/Compiler.js:110:14)
    at Worker.emit (node:events:519:28)
    at MessagePort.<anonymous> (node:internal/worker:263:53)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:822:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'ERR_UNHANDLED_ERROR',
  context: {}
}

Node.js v21.6.1

```
I've very new to react-native, so just trying to get some pointers on where to go next and how to troubleshoot this.

**Comment by jbroma** [comment] 2024-02-29 13:56
hi @thomasreiser 

I will not be able to determine the cause of this without a reproduction repository. As switching to newer `node` version helped with similar issue, you might try doing that. In case you want to provide a reproduction repository, please also provide what node version you were using, thanks!

Since this issue is 2 months old I'll close it for now, but will reopen when reproduction repository is provided.

**Closed by jbroma** 2024-02-29 13:56 UTC
