### ISSUE TITLE
React fast refresh doesn't work

### ISSUE THREAD

**Issue by tom-sherman** [callstack/repack#161] opened 2022-02-12 12:52 UTC
I'm using a completely fresh react native project and the example webpack config. Every time I change a file the app does a full reload.

Looks like I'm getting an error "Cannot find update - full reload needed"

```
ℹ [13:06:06.381Z][Console] [HMRClient] Connected 
ℹ [13:06:11.103Z][Console] [HMRClient] Bundle rebuilding {"name": undefined} 
ℹ [13:06:12.095Z][LoggerPlugin] Bundle built { time: 848 } 
ℹ [13:06:12.140Z][Console] [HMRClient] Bundle rebuilt {"name": "", "time": 848} 
ℹ [13:06:12.140Z][Console] [HMRClient] Checking for updates on the server... 
ℹ [13:06:12.154Z][Console] [HMRClient] Bundle rebuilding {"name": undefined} 
ℹ [13:06:12.165Z][webpack-dev-middleware] wait until bundle finished: /main.a7de78ea630f9c9142ab.hot-update.json 
ℹ [13:06:12.769Z][LoggerPlugin] Bundle built { time: 540 } 
ℹ [13:06:12.792Z][Console] [HMRClient] Bundle rebuilt {"name": "", "time": 540} 
ℹ [13:06:12.795Z][DevServer@ios] Route GET:/main.a7de78ea630f9c9142ab.hot-update.json not found 
⚠ [13:06:12.805Z][Console] [HMRClient] Cannot find update - full reload needed 
ℹ [13:06:12.830Z][DevServerProxy] fetching from remote server {
  source: 'http://localhost:55871/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.RepackDemo'
} 
ℹ [13:06:12.838Z][DevServerProxy] response received 
ℹ [13:06:12.841Z][DevServerProxy] React Native client disconnected { clientId: 'client#7' } 
ℹ [13:06:12.843Z][DevServer@ios] HMR client disconnected { clientId: 'client#7' } 
ℹ [13:06:13.057Z][DevServerProxy] React Native client connected { clientId: 'client#8' } 
ℹ [13:06:13.234Z][DevServer@ios] HMR client connected { clientId: 'client#8' } 
ℹ [13:06:13.236Z][Console] [HMRClient] Connecting... {"url": "ws://localhost:55871/__hmr"} 
ℹ [13:06:13.259Z][Console] Running "RepackDemo" with {"rootTag":371,"initialProps":{}} 
ℹ [13:06:13.393Z][Console] [HMRClient] Connected
```

**Comment by joe06102** [comment] 2022-02-14 02:30
I got the same issue sometimes, wondering if it is an issue related to the older version of pmmmwh/react-refresh-webpack-plugin.
I'll try to upgrade the react-refresh-webpack-plugin to the 5.x version later.

**Comment by joe06102** [comment] 2022-02-18 06:22
It appears to be a bug of the webpack ([HMR not working on webpack 5.66.0](https://github.com/webpack/webpack/issues/15206)).

There're two ways to fix the problem:

1. downgrade your webpack to 5.65 or earlier versions
2. remove the output.clean in webpack.config.js

**I'm using the webpack@5.68.0. I remove the output.clean and the HMR works like a charm!**

**Comment by tom-sherman** [comment] 2022-02-18 09:46
Why would updating the fast-refresh packages also fix the issue? 🤔

**Comment by piccinnigius** [comment] 2022-02-21 18:06
> It appears to be a bug of the webpack ([HMR not working on webpack 5.66.0](https://github.com/webpack/webpack/issues/15206)).
> 
> There're two ways to fix the problem:
> 
> 1. downgrade your webpack to 5.65 or earlier versions
> 2. remove the output.clean in webpack.config.js
> 
> **I'm using the webpack@5.68.0. I remove the output.clean and the HMR works like a charm!**

fixed by doing both, ty 👍

**Comment by mahi8813** [comment] 2022-02-21 20:06
@piccinnigius I tried your solution. It is not working for me. Did you set cache: false for this work?

**Comment by zamotany** [comment] 2022-07-11 13:00
Closing since the issue is somewhere between `@pmmmwh/react-refresh-webpack-plugin`, `react-refresh` and Webpack, not inside Re.Pack.

In upcoming version 3 of Re.Pack `@pmmmwh/react-refresh-webpack-plugin` got upgraded to `0.5.7` and `react-refresh` to `0.14.0`.

**Closed by zamotany** 2022-07-11 13:00 UTC
