### ISSUE TITLE
resolveRemoteChunk url is not working on my side

### ISSUE THREAD

**Issue by usman852** [callstack/repack#87] opened 2021-09-21 06:12 UTC
ChunkManager.configure({
  resolveRemoteChunk: async (chunkId) => {
    return {
      url: `http://localhost:5000/${chunkId}`,
    };
  },
});

@zamotany

**Comment by zamotany** [comment] 2021-09-21 11:19
I need some more information what's happening:
1. Do you test application in development mode or production?
2. Do you have additional server running on `localhost:5000` which would serve the remote chunks?
3. Do you get any errors in the console/XCode/Android Studio?
4. Are you using Re.Pack's native module?
5. Are you using dynamic `import(...)` function or you're doing code splitting manually?

**Comment by usman852** [comment] 2021-09-21 11:38
1. We'r testing on development mode.
2. I write localhost just for testing , but i'm using my own link, in which i upload JS file.
3. No i did'nt get any error from android studio. Application is running but chunk.manager function is not invoked.
4. I did'nt get your point but i'm using repack library.
5. Yes

**Comment by zamotany** [comment] 2021-09-21 11:43
Ok, in development mode all chunks are resolved and downloaded from the Development server. So `resolveRemoteChunk` is not called by design. By default the `resolveRemoteChunk` is only used in production mode.

Today I released a new version that allows to force the resolution to happen through `resolveRemoteChunk`.

Please read the updated documentation:
- https://re-pack.netlify.app/docs/api/react-native/classes/ChunkManager
- https://re-pack.netlify.app/docs/api/react-native/interfaces/ChunkManagerConfig#forceremotechunkresolution

In order to use Code Splitting from Webpack & Re.Pack in React Native, Re.Pack provides a native module. It should be automatically linked, but it's good to do `pod install` for iOS to make sure it's picked up.

**Comment by zamotany** [comment] 2021-09-21 11:58
I'm going to close this issue for now. If there are any more problems, feel free to reopen it.

**Closed by zamotany** 2021-09-21 11:58 UTC
Labels: question

**Comment by usman852** [comment] 2021-09-21 12:02
Thank You soo much @zamotany

**Comment by zamotany** [comment] 2022-02-11 13:43
What's the error message of the crash you're getting?
