### ISSUE TITLE
Not able to migrate existing metro project to Re.pack: Cannot read the property of undefined

### ISSUE THREAD

**Issue by kartik-stan** [callstack/repack#296] opened 2023-01-24 12:06 UTC
I am trying to migrate an already existing app which is on Metro to Repack and I am getting various errors related my JS code which works fine with Metro.

**Comment by thymikee** [comment] 2023-01-24 17:19
Would be great to have the errors you're getting, ideally with a repro we could download and inspect :)

**Comment by kartik-stan** [comment] 2023-01-30 07:29
Here is my webpack.config.mjs

`import path from 'path';
import TerserPlugin from 'terser-webpack-plugin';
import * as Repack from '@callstack/repack';

/**
 * More documentation, installation, usage, motivation and differences with Metro is available at:
 * https://github.com/callstack/repack/blob/main/README.md
 *
 * The API documentation for the functions and plugins used in this file is available at:
 * https://re-pack.netlify.app/
 */

/**
 * Webpack configuration.
 * You can also export a static object or a function returning a Promise.
 *
 * @param env Environment options passed from either Webpack CLI or React Native CLI
 *            when running with `react-native start/bundle`.
 */
export default (env) => {
  const {
    mode = 'development',
    context = Repack.getDirname(import.meta.url),
    entry = './index.js',
    platform = process.env.PLATFORM,
    minimize = mode === 'production',
    devServer = undefined,
    bundleFilename = undefined,
    sourceMapFilename = undefined,
    assetsPath = undefined,
    reactNativePath = new URL('./node_modules/react-native', import.meta.url)
      .pathname,
  } = env;
  const dirname = Repack.getDirname(import.meta.url);

  if (!platform) {
    throw new Error('Missing platform');
  }

    /**
   * Using Module Federation might require disabling hmr.
   * Uncomment below to set `devServer.hmr` to `false`.
   *
   * Keep in mind that `devServer` object is not available
   * when running `webpack-bundle` command. Be sure
   * to check its value to avoid accessing undefined value,
   * otherwise an error might occur.
   */
  // if (devServer) {
  //   devServer.hmr = false;
  // }
  
  /**
   * Depending on your Babel configuration you might want to keep it.
   * If you don't use `env` in your Babel config, you can remove it.
   *
   * Keep in mind that if you remove it you should set `BABEL_ENV` or `NODE_ENV`
   * to `development` or `production`. Otherwise your production code might be compiled with
   * in development mode by Babel.
   */
  process.env.BABEL_ENV = mode;

  return {
    mode,
    /**
     * This should be always `false`, since the Source Map configuration is done
     * by `SourceMapDevToolPlugin`.
     */
    devtool: false,
    context,
    /**
     * `getInitializationEntries` will return necessary entries with setup and initialization code.
     * If you don't want to use Hot Module Replacement, set `hmr` option to `false`. By default,
     * HMR will be enabled in development mode.
     */
    entry: [
      ...Repack.getInitializationEntries(reactNativePath, {
        hmr: devServer && devServer.hmr,
      }),
      entry,
    ],
    resolve: {
      /**
       * `getResolveOptions` returns additional resolution configuration for React Native.
       * If it's removed, you won't be able to use `<file>.<platform>.<ext>` (eg: `file.ios.js`)
       * convention and some 3rd-party libraries that specify `react-native` field
       * in their `package.json` might not work correctly.
       */
      ...Repack.getResolveOptions(platform),
      modules: [
        path.resolve(dirname, 'node_modules'),
        'node_modules',
        'invariant',
        '@react-native-async-storage/async-storage',
        '@walletconnect/react-native-dapps',
        '@walletconnect/client',
        'keyvaluestorage',
        'recoil',
        '@react-navigation/native',
        'recompose',
        'browserify-sign',
        'engine.io-client',
        'socket.io-parser',
        'socket.io-client',
        'structError',
        'react-native-device-info',
        'react-native-redash'
      ],
      alias: {
        '@walletconnect/client': path.resolve(
          dirname,
          'node_modules',
          '@walletconnect/client/dist/umd/index.min',
        ),
      },

      /**
       * Uncomment this to ensure all `react-native*` imports will resolve to the same React Native
       * dependency. You might need it when using workspaces/monorepos or unconventional project
       * structure. For simple/typical project you won't need it.
       */
      // alias: {
      //   'react-native': reactNativePath,
      // },
    },
    /**
     * Configures output.
     * It's recommended to leave it as it is unless you know what you're doing.
     * By default Webpack will emit files into the directory specified under `path`. In order for the
     * React Native app use them when bundling the `.ipa`/`.apk`, they need to be copied over with
     * `Repack.OutputPlugin`, which is configured by default inside `Repack.RepackPlugin`.
     */
    output: {
      clean: true,
      path: path.join(dirname, 'build/generated', platform),
      filename: 'index.bundle',
      chunkFilename: '[name].chunk.bundle',
      publicPath: Repack.getPublicPath({platform, devServer}),
    },
    /**
     * Configures optimization of the built bundle.
     */
    optimization: {
      /** Enables minification based on values passed from React Native CLI or from fallback. */
      minimize,
      /** Configure minimizer to process the bundle. */
      minimizer: [
        new TerserPlugin({
          test: /\.(js)?bundle(\?.*)?$/i,
          /**
           * Prevents emitting text file with comments, licenses etc.
           * If you want to gather in-file licenses, feel free to remove this line or configure it
           * differently.
           */
          extractComments: false,
          terserOptions: {
            format: {
              comments: false,
            },
          },
        }),
      ],
      chunkIds: 'named',
    },
    module: {
      /**
       * This rule will process all React Native related dependencies with Babel.
       * If you have a 3rd-party dependency that you need to transpile, you can add it to the
       * `include` list.
       *
       * You can also enable persistent caching with `cacheDirectory` - please refer to:
       * https://github.com/babel/babel-loader#options
       */
      rules: [
        {
          test: /\.[jt]sx?$/,
          include: [
            /node_modules(.*[/\\])+react/,
            /node_modules(.*[/\\])+@react-native/,
            /node_modules(.*[/\\])+@react-navigation/,
            /node_modules(.*[/\\])+@react-navigation\/native/,
            /node_modules(.*[/\\])+@react-native-community/,
            /node_modules(.*[/\\])+@expo/,
            /node_modules(.*[/\\])+pretty-format/,
            /node_modules(.*[/\\])+metro/,
            /node_modules(.*[/\\])+abort-controller/,
            /node_modules(.*[/\\])+@callstack\/repack/,
            /node_modules(.*[/\\])+stan-club/,
            /node_modules(.*[/\\])+sp-react-native-in-app-updates/,
            /node_modules(.*[/\\])+invariant/,
            /node_modules(.*[/\\])+react-native-svg/,
            /node_modules(.*[/\\])+@react-native-community\/datetimepicker/,
            /node_modules(.*[/\\])+@react-native-async-storage\/async-storage/,
            /node_modules(.*[/\\])+@walletconnect\/react-native-dapp/,
            /node_modules(.*[/\\])+@walletconnect\/client/,
            /node_modules(.*[/\\])+keyvaluestorage/,
            /node_modules(.*[/\\])+recoil/,
            /node_modules(.*[/\\])+recompose/,
            /node_modules(.*[/\\])+browserify-sign/,
            /node_modules(.*[/\\])+engine.io-client/,
            /node_modules(.*[/\\])+socket.io-parser/,
            /node_modules(.*[/\\])+socket.io-client/,
            /node_modules(.*[/\\])+superstruct/,
            /node_modules(.*[/\\])+react-native-device-info/,
            /node_modules(.*[/\\])+react-native-redash/,
          ],
          use: 'babel-loader',
        },
        /**
         * Here you can adjust loader that will process your files.
         *
         * You can also enable persistent caching with `cacheDirectory` - please refer to:
         * https://github.com/babel/babel-loader#options
         */
        {
          test: /\.[jt]sx?$/,
          exclude: /node_modules/,
          use: {
            loader: 'babel-loader',
            options: {
              /** Add React Refresh transform only when HMR is enabled. */
              plugins:
                devServer && devServer.hmr
                  ? ['module:react-refresh/babel']
                  : undefined,
            },
          },
        },
        /**
         * This loader handles all static assets (images, video, audio and others), so that you can
         * use (reference) them inside your application.
         *
         * If you wan to handle specific asset type manually, filter out the extension
         * from `ASSET_EXTENSIONS`, for example:
         * ```
         * Repack.ASSET_EXTENSIONS.filter((ext) => ext !== 'svg')
         * ```
         */
        {
          test: Repack.getAssetExtensionsRegExp(Repack.ASSET_EXTENSIONS),
          use: {
            loader: '@callstack/repack/assets-loader',
            options: {
              platform,
              devServerEnabled: Boolean(devServer),
              /**
               * Defines which assets are scalable - which assets can have
               * scale suffixes: `@1x`, `@2x` and so on.
               * By default all images are scalable.
               */
              scalableAssetExtensions: Repack.SCALABLE_ASSETS,
            },
          },
        },
      ],
    },
    plugins: [
      /**
       * Configure other required and additional plugins to make the bundle
       * work in React Native and provide good development experience with
       * sensible defaults.
       *
       * `Repack.RepackPlugin` provides some degree of customization, but if you
       * need more control, you can replace `Repack.RepackPlugin` with plugins
       * from `Repack.plugins`.
       */
      new Repack.RepackPlugin({
        context,
        mode,
        platform,
        devServer,
        output: {
          bundleFilename,
          sourceMapFilename,
          assetsPath,
        },
      }),
    ],
  };
};`

This is the error which I am getting
<img width="349" alt="image" src="https://user-images.githubusercontent.com/111050644/215412655-95fce698-aaaa-4c1f-8b40-78a976c86dee.png">

RootNavigation.js file
`import { createNavigationContainerRef } from '@react-navigation/native';

export const NavigationRef = createNavigationContainerRef();

export function movetoScreen(name, params) {
  if (NavigationRef?.isReady?.()) {
    NavigationRef?.navigate?.(name, params);
  } else {
    setTimeout(() => {
      movetoScreen?.(name, params);
    }, 1000);
  }
}
`

`movetoScreen` function is being imported and used in APICalls.js file
if I comment the import in APICalls.js the above error will not come.

This scenario is occurring at many places. And the code base works fine with Metro I think there is some issue with the webpack config.

Basic folder structure
index.js
RootNavigation.js
src
  |-- apis/APICalls.js

I will try to reproduce this issue in a seperate repo and provide the link for that too. Till then do let me know if there is anything else I can provide to help you.

**Comment by kartik-stan** [comment] 2023-01-30 07:33
### Here is my webpack.config.mjs

```
import path from 'path';
import TerserPlugin from 'terser-webpack-plugin';
import * as Repack from '@callstack/repack';

/**

More documentation, installation, usage, motivation and differences with Metro is available at:
https://github.com/callstack/repack/blob/main/README.md
The API documentation for the functions and plugins used in this file is available at:
https://re-pack.netlify.app/
*/
/**

Webpack configuration.
You can also export a static object or a function returning a Promise.
@param env Environment options passed from either Webpack CLI or React Native CLI
       when running with `react-native start/bundle`.
*/
export default (env) => {
const {
mode = 'development',
context = Repack.getDirname(import.meta.url),
entry = './index.js',
platform = process.env.PLATFORM,
minimize = mode === 'production',
devServer = undefined,
bundleFilename = undefined,
sourceMapFilename = undefined,
assetsPath = undefined,
reactNativePath = new URL('./node_modules/react-native', import.meta.url)
.pathname,
} = env;
const dirname = Repack.getDirname(import.meta.url);

if (!platform) {
throw new Error('Missing platform');
}

/**
Using Module Federation might require disabling hmr.
Uncomment below to set devServer.hmr to false.
Keep in mind that devServer object is not available
when running webpack-bundle command. Be sure
to check its value to avoid accessing undefined value,
otherwise an error might occur.
*/
// if (devServer) {
// devServer.hmr = false;
// }
/**

Depending on your Babel configuration you might want to keep it.
If you don't use env in your Babel config, you can remove it.
Keep in mind that if you remove it you should set BABEL_ENV or NODE_ENV
to development or production. Otherwise your production code might be compiled with
in development mode by Babel.
*/
process.env.BABEL_ENV = mode;
return {
mode,
/**
* This should be always false, since the Source Map configuration is done
* by SourceMapDevToolPlugin.
/
devtool: false,
context,
/*
* getInitializationEntries will return necessary entries with setup and initialization code.
* If you don't want to use Hot Module Replacement, set hmr option to false. By default,
* HMR will be enabled in development mode.
/
entry: [
...Repack.getInitializationEntries(reactNativePath, {
hmr: devServer && devServer.hmr,
}),
entry,
],
resolve: {
/*
* getResolveOptions returns additional resolution configuration for React Native.
* If it's removed, you won't be able to use <file>.<platform>.<ext> (eg: file.ios.js)
* convention and some 3rd-party libraries that specify react-native field
* in their package.json might not work correctly.
*/
...Repack.getResolveOptions(platform),
modules: [
path.resolve(dirname, 'node_modules'),
'node_modules',
'invariant',
'@react-native-async-storage/async-storage',
'@walletconnect/react-native-dapps',
'@walletconnect/client',
'keyvaluestorage',
'recoil',
'@react-navigation/native',
'recompose',
'browserify-sign',
'engine.io-client',
'socket.io-parser',
'socket.io-client',
'structError',
'react-native-device-info',
'react-native-redash'
],
alias: {
'@walletconnect/client': path.resolve(
dirname,
'node_modules',
'@walletconnect/client/dist/umd/index.min',
),
},

  /**
   * Uncomment this to ensure all `react-native*` imports will resolve to the same React Native
   * dependency. You might need it when using workspaces/monorepos or unconventional project
   * structure. For simple/typical project you won't need it.
   */
  // alias: {
  //   'react-native': reactNativePath,
  // },
},
/**
 * Configures output.
 * It's recommended to leave it as it is unless you know what you're doing.
 * By default Webpack will emit files into the directory specified under `path`. In order for the
 * React Native app use them when bundling the `.ipa`/`.apk`, they need to be copied over with
 * `Repack.OutputPlugin`, which is configured by default inside `Repack.RepackPlugin`.
 */
output: {
  clean: true,
  path: path.join(dirname, 'build/generated', platform),
  filename: 'index.bundle',
  chunkFilename: '[name].chunk.bundle',
  publicPath: Repack.getPublicPath({platform, devServer}),
},
/**
 * Configures optimization of the built bundle.
 */
optimization: {
  /** Enables minification based on values passed from React Native CLI or from fallback. */
  minimize,
  /** Configure minimizer to process the bundle. */
  minimizer: [
    new TerserPlugin({
      test: /\.(js)?bundle(\?.*)?$/i,
      /**
       * Prevents emitting text file with comments, licenses etc.
       * If you want to gather in-file licenses, feel free to remove this line or configure it
       * differently.
       */
      extractComments: false,
      terserOptions: {
        format: {
          comments: false,
        },
      },
    }),
  ],
  chunkIds: 'named',
},
module: {
  /**
   * This rule will process all React Native related dependencies with Babel.
   * If you have a 3rd-party dependency that you need to transpile, you can add it to the
   * `include` list.
   *
   * You can also enable persistent caching with `cacheDirectory` - please refer to:
   * https://github.com/babel/babel-loader#options
   */
  rules: [
    {
      test: /\.[jt]sx?$/,
      include: [
        /node_modules(.*[/\\])+react/,
        /node_modules(.*[/\\])+@react-native/,
        /node_modules(.*[/\\])+@react-navigation/,
        /node_modules(.*[/\\])+@react-navigation\/native/,
        /node_modules(.*[/\\])+@react-native-community/,
        /node_modules(.*[/\\])+@expo/,
        /node_modules(.*[/\\])+pretty-format/,
        /node_modules(.*[/\\])+metro/,
        /node_modules(.*[/\\])+abort-controller/,
        /node_modules(.*[/\\])+@callstack\/repack/,
        /node_modules(.*[/\\])+stan-club/,
        /node_modules(.*[/\\])+sp-react-native-in-app-updates/,
        /node_modules(.*[/\\])+invariant/,
        /node_modules(.*[/\\])+react-native-svg/,
        /node_modules(.*[/\\])+@react-native-community\/datetimepicker/,
        /node_modules(.*[/\\])+@react-native-async-storage\/async-storage/,
        /node_modules(.*[/\\])+@walletconnect\/react-native-dapp/,
        /node_modules(.*[/\\])+@walletconnect\/client/,
        /node_modules(.*[/\\])+keyvaluestorage/,
        /node_modules(.*[/\\])+recoil/,
        /node_modules(.*[/\\])+recompose/,
        /node_modules(.*[/\\])+browserify-sign/,
        /node_modules(.*[/\\])+engine.io-client/,
        /node_modules(.*[/\\])+socket.io-parser/,
        /node_modules(.*[/\\])+socket.io-client/,
        /node_modules(.*[/\\])+superstruct/,
        /node_modules(.*[/\\])+react-native-device-info/,
        /node_modules(.*[/\\])+react-native-redash/,
      ],
      use: 'babel-loader',
    },
    /**
     * Here you can adjust loader that will process your files.
     *
     * You can also enable persistent caching with `cacheDirectory` - please refer to:
     * https://github.com/babel/babel-loader#options
     */
    {
      test: /\.[jt]sx?$/,
      exclude: /node_modules/,
      use: {
        loader: 'babel-loader',
        options: {
          /** Add React Refresh transform only when HMR is enabled. */
          plugins:
            devServer && devServer.hmr
              ? ['module:react-refresh/babel']
              : undefined,
        },
      },
    },
    /**
     * This loader handles all static assets (images, video, audio and others), so that you can
     * use (reference) them inside your application.
     *
     * If you wan to handle specific asset type manually, filter out the extension
     * from `ASSET_EXTENSIONS`, for example:
     * ```
     * Repack.ASSET_EXTENSIONS.filter((ext) => ext !== 'svg')
     * ```
     */
    {
      test: Repack.getAssetExtensionsRegExp(Repack.ASSET_EXTENSIONS),
      use: {
        loader: '@callstack/repack/assets-loader',
        options: {
          platform,
          devServerEnabled: Boolean(devServer),
          /**
           * Defines which assets are scalable - which assets can have
           * scale suffixes: `@1x`, `@2x` and so on.
           * By default all images are scalable.
           */
          scalableAssetExtensions: Repack.SCALABLE_ASSETS,
        },
      },
    },
  ],
},
plugins: [
  /**
   * Configure other required and additional plugins to make the bundle
   * work in React Native and provide good development experience with
   * sensible defaults.
   *
   * `Repack.RepackPlugin` provides some degree of customization, but if you
   * need more control, you can replace `Repack.RepackPlugin` with plugins
   * from `Repack.plugins`.
   */
  new Repack.RepackPlugin({
    context,
    mode,
    platform,
    devServer,
    output: {
      bundleFilename,
      sourceMapFilename,
      assetsPath,
    },
  }),
],
};
};
```

**This is the error which I am getting**
<img width="347" alt="image" src="https://user-images.githubusercontent.com/111050644/215414607-9aa8226c-5ba5-4935-a0af-0c50d59df58e.png">

### RootNavigation.js file
```
import { createNavigationContainerRef } from '@react-navigation/native';

export const NavigationRef = createNavigationContainerRef();

export function movetoScreen(name, params) {
if (NavigationRef?.isReady?.()) {
NavigationRef?.navigate?.(name, params);
} else {
setTimeout(() => {
movetoScreen?.(name, params);
}, 1000);
}
}
```

movetoScreen function is being imported and used in APICalls.js file
if I comment the import in APICalls.js the above error will not come.

This scenario is occurring at many places. And the code base works fine with Metro I think there is some issue with the webpack config.

### Basic folder structure
index.js
RootNavigation.js
src
|-- apis/APICalls.js

I will try to reproduce this issue in a seperate repo and provide the link for that too. Till then do let me know if there is anything else I can provide to help you.

**Comment by malikKartik** [comment] 2023-01-30 09:17
I tried a similar scenario in another app there I am not able to reproduce this issue

**Comment by RafikiTiki** [comment] 2023-01-30 12:07
Please create a minimal reproduction repository in which you can constantly reproduce the issue. I'm going to have some time early next week to take a look into your issue if you'll manage to send the repo link here :)

**Comment by RafikiTiki** [comment] 2023-03-20 09:53
Closing for now, but please feel free to add a reproduction repo that I can use to investigate the problem that you're facing. Otherwise, I'm not able to help you.

**Closed by RafikiTiki** 2023-03-20 09:53 UTC
Labels: question, status:waiting-for-response

**Comment by malikKartik** [comment] 2023-03-29 14:14
@RafikiTiki 
I am able to resolve the issue, we are using wallet connect for which we are using rn-nodify which assigns alternate entry points of some packages for react-native and browser. I have removed those and it worked. But I will have to look for an alternative solution for that. Is there any easier way around it?

here are the fields generated by  rn-nodify

```

  "react-native": {
    "zlib": "browserify-zlib",
    "console": "console-browserify",
    "constants": "constants-browserify",
    "crypto": "react-native-crypto",
    "dns": "dns.js",
    "net": "react-native-tcp",
    "domain": "domain-browser",
    "http": "@tradle/react-native-http",
    "https": "https-browserify",
    "os": "react-native-os",
    "path": "path-browserify",
    "querystring": "querystring-es3",
    "fs": "react-native-level-fs",
    "_stream_transform": "readable-stream/transform",
    "_stream_readable": "readable-stream/readable",
    "_stream_writable": "readable-stream/writable",
    "_stream_duplex": "readable-stream/duplex",
    "_stream_passthrough": "readable-stream/passthrough",
    "dgram": "react-native-udp",
    "stream": "stream-browserify",
    "timers": "timers-browserify",
    "tty": "tty-browserify",
    "vm": "vm-browserify",
    "tls": false
  },
  "browser": {
    "zlib": "browserify-zlib",
    "console": "console-browserify",
    "constants": "constants-browserify",
    "crypto": "react-native-crypto",
    "dns": "dns.js",
    "net": "react-native-tcp",
    "domain": "domain-browser",
    "http": "@tradle/react-native-http",
    "https": "https-browserify",
    "os": "react-native-os",
    "path": "path-browserify",
    "querystring": "querystring-es3",
    "fs": "react-native-level-fs",
    "_stream_transform": "readable-stream/transform",
    "_stream_readable": "readable-stream/readable",
    "_stream_writable": "readable-stream/writable",
    "_stream_duplex": "readable-stream/duplex",
    "_stream_passthrough": "readable-stream/passthrough",
    "dgram": "react-native-udp",
    "stream": "stream-browserify",
    "timers": "timers-browserify",
    "tty": "tty-browserify",
    "vm": "vm-browserify",
    "tls": false
  }
```

**Comment by RafikiTiki** [comment] 2023-03-29 14:30
I changed the title so that people looking for rn-nodeify compatibility with Repack will have an easier time finding that issue.

I'm not familiar with rn-nodeify and how it works so unfortunately I won't be able to help you. If you find a solution or want to discuss some things please write in this issue for the future reference.

**Comment by kartik-stan** [comment] 2023-04-03 10:44
**Update**

anyone is using walletconnect v1 or rn-nodify for any other use case you can do the following to make it work

let say rn-nodify generates the following config in your package.json

```
"react-native": {
    "zlib": "browserify-zlib",
    "console": "console-browserify",
    "constants": "constants-browserify",
    "crypto": "react-native-crypto",
    "dns": "dns.js",
    "net": "react-native-tcp",
    "domain": "domain-browser",
    "http": "@tradle/react-native-http",
    "https": "https-browserify",
    "os": "react-native-os",
    "path": "path-browserify",
    "querystring": "querystring-es3",
    "fs": "react-native-level-fs",
    "_stream_transform": "readable-stream/transform",
    "_stream_readable": "readable-stream/readable",
    "_stream_writable": "readable-stream/writable",
    "_stream_duplex": "readable-stream/duplex",
    "_stream_passthrough": "readable-stream/passthrough",
    "dgram": "react-native-udp",
    "stream": "stream-browserify",
    "timers": "timers-browserify",
    "tty": "tty-browserify",
    "vm": "vm-browserify",
    "tls": false
  }
```

you just need to add following alias in your webpack config file

```
resolve: {
...
    alias: {
        ...
        'path': path.resolve(dirname, 'node_modules', 'path-browserify'),
        'zlib': path.resolve(dirname, 'node_modules', 'browserify-zlib'),
        'console': path.resolve(dirname, 'node_modules', 'console-browserify'),
        'constants': path.resolve(dirname, 'node_modules', 'constants-browserify'),
        'crypto': path.resolve(dirname, 'node_modules', 'react-native-crypto'),
        'dns': path.resolve(dirname, 'node_modules', 'dns.js'),
        'net': path.resolve(dirname, 'node_modules', 'react-native-tcp'),
        'domain': path.resolve(dirname, 'node_modules', 'domain-browser'),
        'http': path.resolve(dirname, 'node_modules', '@tradle/react-native-http'),
        'https': path.resolve(dirname, 'node_modules', 'https-browserify'),
        'os': path.resolve(dirname, 'node_modules', 'react-native-os'),
        'querystring': path.resolve(dirname, 'node_modules', 'querystring-es3'),
        'fs': path.resolve(dirname, 'node_modules', 'react-native-level-fs'),
        '_stream_transform': path.resolve(dirname, 'node_modules', 'readable-stream/transform'),
        '_stream_readable': path.resolve(dirname, 'node_modules', 'readable-stream/readable'),
        '_stream_writable': path.resolve(dirname, 'node_modules', 'readable-stream/writable'),
        '_stream_duplex': path.resolve(dirname, 'node_modules', 'readable-stream/duplex'),
        '_stream_passthrough': path.resolve(dirname, 'node_modules', 'readable-stream/passthrough'),
        'dgram': path.resolve(dirname, 'node_modules', 'react-native-udp'),
        'stream': path.resolve(dirname, 'node_modules', 'stream-browserify'),
        'timers': path.resolve(dirname, 'node_modules', 'timers-browserify'),
        'tty': path.resolve(dirname, 'node_modules', 'tty-browserify'),
        'vm': path.resolve(dirname, 'node_modules', 'vm-browserify'),
        'tls': false,
      }
...
}
```

**Comment by eduardorfreitas93** [comment] 2023-07-05 15:24
@kartik-stan I'm not using rn-nodify, I'm trying to migrate an existing project to repack, and I'm encountering the same initial error. If I add a setTimeout, it works.

```

setTimeout(() => {
movetoScreen?.(name, params);
}, 1000);
```

**Comment by eduardorfreitas93** [comment] 2023-07-05 15:26
It works.
```
setTimeout(() => {
  console.log(store)
}, 100)
```

It doesn't work.
```
console.log(store)
```

**Comment by vlack-coder** [comment] 2024-04-28 03:05
Hi @kartik-stan  @malikKartik  How where you able to go about this.
I am trying to use react native crypto which requires rn_nodeify installation....
It works fine on metro  but on repack it doesn't... I was able to run the app on repack with no error but crypto library is not working and it is not grtting logged.. I can not log the process library in shim.js too
