### ISSUE TITLE
Error: Unhandled error. ([ScriptManager] Failed to load script:)

### ISSUE THREAD

**Issue by LeVanTrangz** [callstack/repack#636] opened 2024-06-04 10:33 UTC
Hello everyone, I encountered an app crash problem when moving from host-app to mini-app on Android release and I had to use fire-base to log this error, I tried many ways to fix it but to no avail. Maybe, I hope there is a solution

---
---
Fatal Exception: com.facebook.react.common.JavascriptException
Error: Unhandled error. ([ScriptManager] Failed to load script:) This error is located at: in Lazy in Suspense in Unknown in Unknown in Unknown in Unknown in RCTView in Unknown in m in RCTView in Unknown in RNSScreen in Unknown in i in Suspense in Unknown in N in t in t in b in i in Suspense in Unknown in N in RNSScreenStack in ScreenStack in w in RCTView in Unknown in A in Unknown in Unknown in i in Unknown in Unknown in Unknown in Unknown in Unknown in Unknown in Unknown in f in Unknown in A in Unknown in Unknown in RNCSafeAreaProvider in Unknown in NativeBaseConfigProviderProvider in Unknown in Unknown in Unknown in RCTView in Unknown in RCTView in Unknown in t, stack: <unknown>@1:5816222 value@1:2267478 <unknown>@1:2269254 generatorResume@-1 t@1:6490118 s@1:6490366 <unknown>@1:6282645 <unknown>@1:6282672 <unknown>@1:5177564 v@1:5176313 y@1:5176708 callReactNativeMicrotasks@1:5178951 value@1:5007810 <unknown>@1:5005908 value@1:5007454 value@1:5005866 value@-1 value@-1
com.facebook.react.modules.core.ExceptionsManagerModule.reportException (ExceptionsManagerModule.java:75)
java.lang.reflect.Method.invoke (Method.java)
com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:142)
com.facebook.react.bridge.JavaModuleWrapper.invoke (Unknown Source:21)
com.facebook.jni.NativeRunnable.run (SourceFile)
android.os.Handler.handleCallback (Handler.java:958)

android.os.Handler.dispatchMessage (Handler.java:99)
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage
android.os.Looper.loopOnce (Looper.java:230)

android.os.Looper.loop (Looper.java:319)
com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run (Unknown Source:37)
java.lang.Thread.run (Thread.java:1012)

--
--
Đây là những thứ tôi đang sử dụng, nếu cần thêm gì tôi sẽ cung cấp thêm

"dependencies": {
    "@react-native-async-storage/async-storage": "1.22.1",
    "@react-native-community/blur": "4.4.0",
    "@react-native-community/datetimepicker": "7.6.2",
    "@react-native-community/netinfo": "11.3.0",
    "@react-native-firebase/app": "^20.0.0",
    "@react-native-firebase/crashlytics": "^20.0.0",
    "@react-native-masked-view/masked-view": "0.3.1",
    "@react-navigation/material-bottom-tabs": "6.2.5",
    "@react-navigation/native": "6.0.14",
    "@react-navigation/native-stack": "6.9.2",
    "@reduxjs/toolkit": "2.2.3",
    "@shopify/flash-list": "1.6.3",
    "i18next": "23.10.1",
    "moment": "2.30.1",
    "native-base": "3.4.28",
    "net": "^1.0.2",
    "react": "18.2.0",
    "react-i18next": "14.1.0",
    "react-native": "0.73.4",
    "react-native-base64": "^0.2.1",
    "react-native-calendars": "1.1304.0",
    "react-native-fs": "2.20.0",
    "react-native-gesture-handler": "2.15.0",
    "react-native-haptic-feedback": "2.2.0",
    "react-native-image-crop-picker": "^0.41.1",
    "react-native-linear-gradient": "2.8.3",
    "react-native-nfc-manager": "^3.14.12",
    "react-native-pager-view": "6.2.3",
    "react-native-reanimated": "3.7.1",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "3.29.0",
    "react-native-shimmer-placeholder": "2.0.9",
    "react-native-size-matters": "^0.4.2",
    "react-native-svg": "14.1.0",
    "react-native-tab-view": "3.5.2",
    "react-native-touch-id": "4.4.1",
    "react-native-ui-lib": "7.16.0",
    "react-native-uuid": "^2.0.1",
    "react-native-vision-camera": "^3.9.0",
    "react-native-web": "0.19.10",
    "react-native-webview": "13.8.1",
    "react-redux": "9.1.0",
    "redux": "5.0.1",
    "sockjs-client": "1.6.1",
    "stompjs": "2.3.3",
    "zustand": "4.5.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@callstack/repack": "^3.7.0",
    "@react-native/babel-preset": "0.73.21",
    "@react-native/eslint-config": "0.73.2",
    "@react-native/metro-config": "0.73.5",
    "@react-native/typescript-config": "0.73.1",
    "@types/react": "^18.2.6",
    "@types/react-native-base64": "^0.2.2",
    "@types/react-test-renderer": "^18.0.0",
    "@types/sockjs-client": "^1.5.4",
    "@types/stompjs": "^2.3.9",
    "babel-jest": "^29.6.3",
    "babel-loader": "^9.1.3",
    "eslint": "^8.19.0",
    "file-loader": "^6.2.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "terser-webpack-plugin": "^5.3.10",
    "typescript": "5.0.4",
    "webpack": "^5.90.3",
    "webpack-cli": "^5.1.4"
  },
  
----
My webpack.config.mjs   

export default (env) => {
  const {
    mode = 'production',
    context = Repack.getDirname(import.meta.url),
    entry = './index.js',
    platform = process.env.PLATFORM,
    minimize = mode === 'production',
    devServer = undefined,
    bundleFilename = undefined,
    sourceMapFilename = undefined,
    assetsPath = undefined,
    reactNativePath = new URL('./node_modules/react-native', import.meta.url)
      .pathname,
  } = env;
  
  const dirname = Repack.getDirname(import.meta.url);

  if (!platform) {
    throw new Error('Missing platform');
  }

  /**
 * Using Module Federation might require disabling hmr.
 * Uncomment below to set devServer.hmr to false.
 *
 * Keep in mind that devServer object is not available
 * when running webpack-bundle command. Be sure
 * to check its value to avoid accessing undefined value,
 * otherwise an error might occur.
 */
  // if (devServer) {
  //   devServer.hmr = false;
  // }

  /**
   * Depending on your Babel configuration you might want to keep it.
   * If you don't use env in your Babel config, you can remove it.
   *
   * Keep in mind that if you remove it you should set BABEL_ENV or NODE_ENV
   * to development or production. Otherwise your production code might be compiled with
   * in development mode by Babel.
   */
  process.env.BABEL_ENV = mode;

  return {
    mode,
    /**
     * This should be always false, since the Source Map configuration is done
     * by SourceMapDevToolPlugin.
     */
    devtool: false,
    context,
    /**
     * getInitializationEntries will return necessary entries with setup and initialization code.
     * If you don't want to use Hot Module Replacement, set hmr option to false. By default,
     * HMR will be enabled in development mode.
     */
    entry: [
      ...Repack.getInitializationEntries(reactNativePath, {
        hmr: devServer && devServer.hmr,
      }),
      entry,
    ],
    resolve: {
      /**
       * getResolveOptions returns additional resolution configuration for React Native.
       * If it's removed, you won't be able to use <file>.<platform>.<ext> (eg: file.ios.js)
       * convention and some 3rd-party libraries that specify react-native field
       * in their package.json might not work correctly.
       */
      ...Repack.getResolveOptions(platform),

      /**
       * Uncomment this to ensure all react-native* imports will resolve to the same React Native
       * dependency. You might need it when using workspaces/monorepos or unconventional project
       * structure. For simple/typical project you won't need it.
       */
      alias: {
        'react-native': reactNativePath,
        reselect: path.resolve(
          './node_modules/reselect/dist/reselect.legacy-esm.js',
        ),
        redux: path.resolve('./node_modules/redux/dist/redux.legacy-esm.js'),
        'react-redux': path.resolve(
          './node_modules/react-redux/dist/react-redux.legacy-esm.js',
        ),
        immer: path.resolve('./node_modules/immer/dist/immer.legacy-esm.js'),
        '@reduxjs/toolkit': path.resolve(
          './node_modules/@reduxjs/toolkit/dist/redux-toolkit.legacy-esm.js',
        ),
        'redux-thunk': path.resolve(
          './node_modules/redux-thunk/dist/redux-thunk.legacy-esm.js',
        ),
      },
    },
    /**
     * Configures output.
     * It's recommended to leave it as it is unless you know what you're doing.
     * By default Webpack will emit files into the directory specified under path. In order for the
     * React Native app use them when bundling the .ipa`/.apk`, they need to be copied over with
     * Repack.OutputPlugin, which is configured by default inside Repack.RepackPlugin.
     */
    output: {
      // clean: true,
      hashFunction: 'xxhash64',
      path: path.resolve(dirname, 'build/generated', platform),
      filename: 'index.bundle',
      chunkFilename: '[name].chunk.bundle',
      publicPath: Repack.getPublicPath({ platform, devServer }),
    },
    /**
     * Configures optimization of the built bundle.
     */
    optimization: {
      /** Enables minification based on values passed from React Native CLI or from fallback. */
      minimize,
      /** Configure minimizer to process the bundle. */
      minimizer: [
        new TerserPlugin({
          test: /\.(js)?bundle(\?.*)?$/i,
          /**
           * Prevents emitting text file with comments, licenses etc.
           * If you want to gather in-file licenses, feel free to remove this line or configure it
           * differently.
           */
          extractComments: false,
          terserOptions: {
            format: {
              comments: false,
            },
          },
        }),
      ],
      chunkIds: 'named',
    },
    module: {
      /**
       * This rule will process all React Native related dependencies with Babel.
       * If you have a 3rd-party dependency that you need to transpile, you can add it to the
       * include list.
       *
       * You can also enable persistent caching with cacheDirectory - please refer to:
       * [https://github.com/babel/babel-loader#options](https://l.workplace.com/l.php?u=https%3A%2F%2Fgithub.com%2Fbabel%2Fbabel-loader%23options&h=AT03pot3HTsIHxX1lixdTmtU9C_HZjHS7UTaGEA1pCFUBuA0vZTq-UIkY5fdzGPfIXDWrBzORTP0uM2Guw5gX-_cWi2dddlc5Qt0egde6bSlKbX6hbrYL_ETa91G6bNzXPeKEseSaHtPxKx0q5SByqM)
       */
      rules: [
        {
          test: /\.[jt]sx?$/,
          include: [
            /node_modules(.*[/\\])+react\//,
            /node_modules(.*[/\\])+react-native/,
            /node_modules(.*[/\\])+@react-native/,
            /node_modules(.*[/\\])+react-freeze/,
            /node_modules(.*[/\\])+@react-navigation/,
            /node_modules(.*[/\\])+@react-native-community/,
            /node_modules(.*[/\\])+expo/,
            /node_modules(.*[/\\])+pretty-format/,
            /node_modules(.*[/\\])+metro/,
            /node_modules(.*[/\\])+abort-controller/,
            /node_modules(.*[/\\])+@callstack(.*[/\\])+repack/,
            /node_modules(.*[/\\])+react-native-gesture-handler/,
            /node_modules(.*[/\\])+react-native-reanimated/,
            /node_modules(.*[/\\])+react-native-ui-lib/,
            /node_modules(.*[/\\])+native-base/,
            /node_modules(.*[/\\])+@react-stately/,
            /node_modules(.*[/\\])+i18next/,
            /node_modules(.*[/\\])+react-i18next/,
            /node_modules(.*[/\\])+immer/,
            /node_modules(.*[/\\])+redux/,
            /node_modules(.*[/\\])+react-redux/,
            /node_modules(.*[/\\])+@reduxjs(.*[/\\])+toolkit/,
            /node_modules(.*[/\\])+reselect/,
            /node_modules(.*[/\\])+redux-thunk/,
          ],
          use: 'babel-loader',
        },
        /**
         * Here you can adjust loader that will process your files.
         *
         * You can also enable persistent caching with cacheDirectory - please refer to:
         * [https://github.com/babel/babel-loader#options](https://l.workplace.com/l.php?u=https%3A%2F%2Fgithub.com%2Fbabel%2Fbabel-loader%23options&h=AT03pot3HTsIHxX1lixdTmtU9C_HZjHS7UTaGEA1pCFUBuA0vZTq-UIkY5fdzGPfIXDWrBzORTP0uM2Guw5gX-_cWi2dddlc5Qt0egde6bSlKbX6hbrYL_ETa91G6bNzXPeKEseSaHtPxKx0q5SByqM)
         */
        {
          test: /\.[jt]sx?$/,
          exclude: /node_modules/,
          use: {
            loader: 'babel-loader',
            options: {
              /** Add React Refresh transform only when HMR is enabled. */
              plugins:
                devServer && devServer.hmr
                  ? ['module:react-refresh/babel']
                  : undefined,
            },
          },
        },
        // {
        //   test: /\.(png|jpg|gif)$/,
        //   use: {
        //     loader: 'file-loader',
        //     options: {
        //       name: '[path][name].[ext]', // Output path and filename
        //     },
        //   },
        // },
        // {                                                                              
        //   test: /\.(png|svg|jpg|jpeg|gif)$/i,
        //   type: 'asset/resource',
        // },
        // {
        //   test: /\.(woff|woff2|eot|ttf|otf)$/i,
        //   type: 'asset/resource',
        // },
        /**
         * This loader handles all static assets (images, video, audio and others), so that you can
         * use (reference) them inside your application.
         *
         * If you want to handle specific asset type manually, filter out the extension
         * from ASSET_EXTENSIONS, for example:
         * 
         * Repack.ASSET_EXTENSIONS.filter((ext) => ext !== 'svg')
         * 
         */
        {
          test: Repack.getAssetExtensionsRegExp(Repack.ASSET_EXTENSIONS),
          use: {
            loader: '@callstack/repack/assets-loader',
            options: {
              platform,
              inline: true,
              devServerEnabled: Boolean(devServer),
              /**
               * Defines which assets are scalable - which assets can have
               * scale suffixes: @1x, @2x and so on.
               * By default all images are scalable.
               */
              scalableAssetExtensions: Repack.SCALABLE_ASSETS,
            },
          },
        },
      ],
    },
    plugins: [
      /**
       * Configure other required and additional plugins to make the bundle
       * work in React Native and provide good development experience with
       * sensible defaults.
       *
       * Repack.RepackPlugin provides some degree of customization, but if you
       * need more control, you can replace Repack.RepackPlugin with plugins
       * from Repack.plugins.
       */
      new Repack.RepackPlugin({
        context,
        mode,
        platform,
        devServer,
        output: {
          bundleFilename,
          sourceMapFilename,
          assetsPath,
        },
      }),

      new Repack.plugins.ModuleFederationPlugin({
        name: 'host',
        shared: {
          react: {
            singleton: true,
            eager: true,
            requiredVersion: '18.2.0',
          },
          'react-native': {
            singleton: true,
            eager: true,
            requiredVersion: '0.73.4',
          },
          '@react-navigation/native': {
            singleton: true,
            eager: true,
            requiredVersion: '6.0.14',
          },
          '@react-navigation/native-stack': {
            singleton: true,
            eager: true,
            requiredVersion: '6.9.2',
          },
          'react-native-safe-area-context': {
            singleton: true,
            eager: true,
            requiredVersion: '4.5.0',
          },
          '@react-navigation/material-bottom-tabs': {
            singleton: true,
            eager: true,
            requiredVersion: '6.2.5',
          },
          'react-native-screens': {
            singleton: true,
            eager: true,
            requiredVersion: '3.29.0',
          },
          '@react-native-async-storage/async-storage': {
            singleton: true,
            eager: true,
            requiredVersion: '1.22.1',
          },
          '@react-native-masked-view/masked-view': {
            singleton: true,
            eager: true,
            requiredVersion: '0.3.1',
          },
          'react-native-ui-lib': {
            singleton: true,
            eager: true,
            requiredVersion: '7.16.0',
          },
          'moment': {
            singleton: true,
            eager: true,
            requiredVersion: '2.30.1',
          },
          'react-native-reanimated': {
            singleton: true,
            eager: true,
            requiredVersion: '3.7.1',
          },
          '@react-native-community/blur': {
            singleton: true,
            eager: true,
            requiredVersion: '4.4.0',
          },
          '@react-native-community/datetimepicker': {
            singleton: true,
            eager: true,
            requiredVersion: '7.6.2',
          },
          '@react-native-community/netinfo': {
            singleton: true,
            eager: true,
            requiredVersion: '11.3.0',
          },
          '@shopify/flash-list': {
            singleton: true,
            eager: true,
            requiredVersion: '1.6.3',
          },
          'react-native-fs': {
            singleton: true,
            eager: true,
            requiredVersion: '2.20.0',
          },
          'react-native-gesture-handler': {
            singleton: true,
            eager: true,
            requiredVersion: '2.15.0',
          },
          'react-native-haptic-feedback': {
            singleton: true,
            eager: true,
            requiredVersion: '2.2.0',
          },
          'react-native-linear-gradient': {
            singleton: true,
            eager: true,
            requiredVersion: '2.8.3',
          },
          'react-native-shimmer-placeholder': {
            singleton: true,
            eager: true,
            requiredVersion: '2.0.9',
          },
          'react-native-svg': {
            singleton: true,
            eager: true,
            requiredVersion: '14.1.0',
          },
          'react-native-webview': {
            singleton: true,
            eager: true,
            requiredVersion: '13.8.1',
          },
          'native-base': {
            singleton: true,
            eager: true,
            requiredVersion: '3.4.28',
          },
          'react-native-pager-view': {
            singleton: true,
            eager: true,
            requiredVersion: '6.2.3',
          },
          'react-native-tab-view': {
            singleton: true,
            eager: true,
            requiredVersion: '3.5.2',
          },
          'react-native-touch-id': {
            singleton: true,
            eager: true,
            requiredVersion: '4.4.1',
          },
          'react-native-calendars': {
            singleton: true,
            eager: true,
            requiredVersion: '1.1304.0',
          },
          'i18next': {
            singleton: true,
            eager: true,
            requiredVersion: '23.10.1',
          },
          'react-i18next': {
            singleton: true,
            eager: true,
            requiredVersion: '14.1.0',
          },
          'redux': {
            singleton: true,
            eager: true,
            requiredVersion: '5.0.1',
          },
          'react-redux': {
            singleton: true,
            eager: true,
            requiredVersion: '9.1.0',
          },
          '@reduxjs/toolkit': {
            singleton: true,
            eager: true,
            requiredVersion: '2.2.3',
            
            --- 
index.js

![image](https://github.com/callstack/repack/assets/82595505/7fcdf2f5-aa19-4b0a-a60b-3202f9baa67a)
---
My part went from a server application to a small application

![image](https://github.com/callstack/repack/assets/82595505/d1f95d03-ec89-46be-a1cd-f25703e26fd1)

**Comment by jbroma** [comment] 2024-06-14 13:36
Hi @LeVanTrangz, the configuration is very verbose, can you try to reproduce the issue in a more isolated manner and inside of a fresh reproduction repository? Happy to help then 🙏

**Comment by jbroma** [comment] 2024-06-14 15:29
I'm closing this one as it's a duplicate of #631

**Closed by jbroma** 2024-06-14 15:29 UTC
Labels: question
