### ISSUE TITLE
Unable to load mini app with Redux store into Host app

### ISSUE THREAD

**Issue by Akashdeep312** [callstack/repack#736] opened 2024-09-06 16:37 UTC
### Describe the bug

I have a mini app which has  full functionality  and it's own store using redux and redux toolkit , now i want to load into host app which is based of [Super App Showcase](https://github.com/callstack/super-app-showcase) and i'm having the following error

![image](https://github.com/user-attachments/assets/622c6f53-2df3-4f9f-aada-56927d03264e)

mini app that i want to load has following configuration.

```js
<Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        <PaperProvider>
          <ThemeProvider>
            <GestureHandlerRootView style={{flex: 1}}>
              <Stack.Navigator screenOptions={{headerShown: false}}>
                <Stack.Screen name={'BOOK'} component={Booking} />
              </Stack.Navigator>
            </GestureHandlerRootView>
          </ThemeProvider>
        </PaperProvider>
      </PersistGate>
    </Provider>
```

### System Info

```shell
System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M1 Pro
  Memory: 71.06 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.15.0
    path: ~/.nvm/versions/node/v20.15.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v20.15.0/bin/yarn
  npm:
    version: 10.7.0
    path: ~/.nvm/versions/node/v20.15.0/bin/npm
  Watchman:
    version: 2024.07.15.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.11090377
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /opt/homebrew/opt/openjdk@17/bin/javac
  Ruby:
    version: 2.7.4
    path: /Users/aakashdeep/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Re.Pack Version

host: ->"@callstack/repack": "3.7.0",miniapp:->"@callstack/repack": "^4.3.1",

### Reproduction

https://github.com/callstack/news-mini-app-showcase

### Steps to reproduce

creating the a minimal repo, that will take some time for me as the app is fully functional app trying to trim out the features, don't ignore this only because of this news app link repo 😅

**Comment by jbroma** [comment] 2024-09-09 09:17
Hi @Akashdeep312, 

this is not a bug but a configuration error, please take a look here to fix your issue: https://github.com/callstack/repack/issues/500. You should also search for `redux` in the issues, we had a few about it.

I'll close this issue for the reason above - if this is not the case, please submit a new issue and add a minimal reproduction repository link, thanks!

**Closed by jbroma** 2024-09-09 09:17 UTC
Labels: status:new, type:bug
