### ISSUE TITLE
aws-appsync issue

### ISSUE THREAD

**Issue by durkumar** [callstack/repack#653] opened 2024-06-25 06:17 UTC
I am integrated aws-appsync in repack (react native) and its working fine in debug mode but when try create release apk its showing issue

Execution failed for task ':app:createBundleReleaseJsAndAssets'.

But when i comment out "createAuthLink()" apk genration successful

createAuthLink({ url, region, auth }),

can any one help out ?

**Comment by jbroma** [comment] 2024-06-25 06:41
Hi @durkumar,

can you share some more details about the error you're getting during the build? Please also state what version of Re.Pack you are using when this happens.

**Comment by durkumar** [comment] 2024-06-25 06:48
> Hi @durkumar,
> 
> can you share some more details about the error you're getting during the build? Please also state what version of Re.Pack you are using when this happens.

I am sharing my code details
Re.pack version :-  pnpm@9.1.4

import { AuthOptions, createAuthLink } from "aws-appsync-auth-link";
import { createSubscriptionHandshakeLink } from "aws-appsync-subscription-link";
import {
    ApolloClient,
    InMemoryCache,
    HttpLink,
    ApolloLink,
  } from "@apollo/client";
const url = 'https://test.com';
const region = 'ap-southeast-1';

const auth:AuthOptions = {
  type: 'AMAZON_COGNITO_USER_POOLS',
  jwtToken: async () => {
    let token = await AsyncStorage.getItem('token')
  return token
  }
};

const httpLink = new HttpLink({ uri: url });
const link = ApolloLink.from([
   createAuthLink({ url, region, auth }),
   createSubscriptionHandshakeLink({ url, region, auth }, httpLink),
]);

const client = new ApolloClient({
  link,
  cache: new InMemoryCache(),
  defaultOptions: {
    mutate: { errorPolicy: 'ignore' },
  },
});

**Comment by durkumar** [comment] 2024-06-25 08:57
> Re.Pac

error -

* What went wrong:
Execution failed for task ':app:createBundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 2

/@callstack/repack@3.4.0

**Comment by jbroma** [comment] 2024-06-25 09:01
I'm not able to assist you with the information you've provided so far - please create a minimal reproduction repository where the bug is happening (please try to avoid recreating your whole project since I will simply not have enough time to investigate it properly).

You can also try upgrading Re.Pack to the newest version to see if it fixes the issues

**Comment by jbroma** [comment] 2024-06-28 11:06
I'm closing this one since not enough information has been provided to diagnose this issues - please create a new issue with a repro to investigate this further, thanks!

**Closed by jbroma** 2024-06-28 11:06 UTC
