### ISSUE TITLE
Unable to use @sinclair/typebox library

### ISSUE THREAD

**Issue by chakrihacker** [callstack/repack#388] opened 2023-06-22 20:13 UTC
## Environment

react-native: 0.71.10

## Description

1. Install typebox library
2. create any type
3. run the app

See globalThis.BigInt is not a number error

**Comment by jbroma** [comment] 2023-06-22 21:44
Closing this issue as the problem lies with library. I've found out that version `0.25.24` works properly, after that it breaks for both Re.Pack and metro.

In the future, please verify the package works with `metro` first as we can't possibly check every library for compatibility.

**Comment by chakravarthi-bb** [comment] 2023-06-23 04:53
I am able to use this version on metro, I am migrating from metro to webpack

**Comment by chakrihacker** [comment] 2023-06-23 04:54
I am able to use it with metro

I started migrating to repack

**Comment by sinclairzx81** [comment] 2023-06-25 07:21
@chakrihacker Heya, just happened across this issue.

> Closing this issue as the problem lies with library.

Would it be possible to provide a bit more detail around this? Have been able to build TypeBox with `metro@0.76.7`  (although I'm not very familiar with this tool). The error reported here appears to be related to `bigint` types which should be supported on modern JavaScript runtimes. Could this be version issue between repack and metro? (perhaps BigInt support has been added on recent versions, noting a few users have reported bundler issues relating to BigInt)

If there's something that can be done to resolve this issue on TypeBox's side. I'm quite prepared to look into that. BigInt support was added on `typebox@0.26.0`, so revisions seem to line up to suggest this is the core of the problem.

**Comment by jbroma** [comment] 2023-06-27 11:02
Hi @sinclairzx81 & @chakrihacker

First of all, I do apologise for rushing in and closing this issue without much of an explanation. I'll reopen this issue for the time being.

I've created a repo with basic setup [here](https://github.com/jbroma/repack-typebox-bug-repro).

From the start I wasn't able to reproduce the issue with BigInt, but I was still getting errors when using `typebox` with an example taken from `README.md`. I was able to find the root cause of this issue for `Object` but I believe this will be also applicable for other types in your library as well.

Little bit of background: both metro & Re.Pack use `metro-react-native-babel-preset` to transform dependencies into compliant format. One of these transforms that is turned on by default is `@babel/plugin-transform-object-rest-spread` which will transform expressions like `{ ...b, a }` into `Object.assign({ a }, b)`. 

In `typebox` there is a lot of shadowing happening, and this transform will cause errors like `undefined is not a function` because Object will refer to the `function Object` instead of the global `Object`. 

In the repro repository, I've added `patch-package` and modified `typebox` to eliminate this shadowing of global `Object`. This allows the library to work properly without errors. I suspect that there are more issues like this inside of `typebox.js`. Fixing the shadowing of global `Object` was sufficient to get the minimal use-case to work. Please note that there is no shadowing happening inside of the class that exposes the public API of the library.

If you would like to make this library easy to integrate with React-Native ecosystem which still uses a lot of transforms like the one mentioned above, enforcing `eslint` rule [`no-shadow` with `builtinGlobals: true`](https://eslint.org/docs/latest/rules/no-shadow) would eliminate this sort of issues.

There is also another side to this story. Since `react-native@0.70` we have Hermes engine enabled as default. Hermes supports many of these features that are being transformed out of the box. We can modify  `babel.config.js` in a following way:

```js
module.exports = {
  presets: [
    [
      'module:metro-react-native-babel-preset',
      {
        unstable_transformProfile: 'hermes-stable',
      },
    ],
  ],
};
```

For some unknown reason this is not the default even though Hermes is the default JS engine. This eliminates the issue in question altogether as spread syntax isn't getting transformed. 

To sum it all up, for users wanting to use `typebox` you can modify `babel.config.js` and use it out of the box. @chakrihacker please let me know whether this change is sufficient to make the library work.

**Comment by chakrihacker** [comment] 2023-06-27 14:51
Hey @jbroma thanks for the update

**Comment by sinclairzx81** [comment] 2023-06-27 23:09
@chakrihacker Hey thanks for the follow up!

> In the repro repository, I've added patch-package and modified typebox to eliminate this shadowing of global Object. This allows the library to work properly without errors. I suspect that there are more issues like this inside of typebox.js. Fixing the shadowing of global Object was sufficient to get the minimal use-case to work. Please note that there is no shadowing happening inside of the class that exposes the public API of the library.

This is brilliant, thank you very much for tracking down this issue (and for the repro and write up!). Yeah I agree, the transform rewriting spread to `Object.assign(...)` would likely cause quite a few problems. Internal to TypeBox, I do prefix with `globalThis`, but it didn't occur to me auxiliary transforms might applying such transforms without factoring exterior scope (but it does make sense this may not be checked in all cases)

This does sound like a very good justification for using a different naming scheme to try and avoid issues like this. Truly, the information you've provided is exceptionally helpful (as I've had React Native users report similar issues to me in the past without much information to the cause). I'm wondering if bumping the ES target for the transforms might be another viable option.

> To sum it all up, for users wanting to use typebox you can modify babel.config.js and use it out of the box.

Just to note, I wouldn't expect updates in TypeBox to be able to resolve this issue in the near term (as the updates would be vast), but interested to know if the suggested configurations help resolve things. A resolution here may help serve as a reference point for users in the interim and give me a bit of time to get a solution in place.

Reference https://github.com/sinclairzx81/typebox/issues/333

Thanks again!
S

**Closed** 2023-06-28 13:49 UTC
