### ISSUE TITLE
FATAL ERROR: v8::FromJust Maybe value is Nothing.

### ISSUE THREAD

**Issue by sschottler** [callstack/repack#323] opened 2023-03-29 18:16 UTC
Hello, I get this `"FATAL ERROR: v8::FromJust Maybe value is Nothing."` error message related to nodejs worker threads with either the `.mjs` or `.cjs` webpack.config template when I run `react-native webpack-start`. I have tried installing other node versions (v16.10.0) and running `yarn cache clean` and `npm cache clean --force` as some google search results for `"FATAL ERROR: v8::FromJust Maybe value is Nothing"` suggested and I still get this error. Any insight as to what might be causing this or how I can troubleshoot this would be appreciated. Thank you!

<img width="1295" alt="updated-error" src="https://user-images.githubusercontent.com/36276352/229896957-3bac24d1-d3f2-4742-8aec-b4ddbd493311.png">

**Comment by RafikiTiki** [comment] 2023-04-03 10:09
Could you share a minimal reproduction repository with a list of steps to follow to see the behavior you described?

**Comment by sschottler** [comment] 2023-04-03 17:00
I am only experiencing it with a large monorepo of private code. The closest I have come to replicating it in a smaller example is hitting ctrl + c in the terminal of the webpack dev server of either a federated module or host after it has started bundling in response to first request and before it has completed. Sometimes I will see the same `FATAL ERROR: v8::FromJust Maybe value is Nothing` general message. So I think something is killing the webpack dev server process during the bundling of the larger monorepo app. I see nodejs memory and CPU usage spike in activity monitor on mac before it happens. I am not sure if it's related to the large amount of JS to process, the fact that it's a monorepo and symlinks could be causing confusion or cyclic dependencies causing CPU/memory to spike, or something else? I know it works for metro bundler and I am trying to compare the config from metro to webpack and see if there is something I need to set in webpack that metro already handles. I am able to get it to bundle in a smaller stripped down version of this app without as many of the monorepo packages so something related to the amount of JS and symlinks. Sorry I can't provide a better reproducible example. I will update this issue as I learn more in case others run into similar problem

**Comment by RafikiTiki** [comment] 2023-04-17 13:59
A quick google search revealed that many packages are affected by the `FATAL ERROR: v8::FromJust Maybe value is Nothing` error, and it looks like a generic error that can happen for many reasons. There's even one in the node repository (https://github.com/nodejs/node/issues/6899). Without an environment where the issue can be easily reproduced most of the time, I won't be able to help here.

One quick fix might be to use a more up-to-date version of the node itself (in your error log, I can see you're using node v14, which is pretty old and will hit the end of life in two weeks – https://nodejs.dev/en/about/releases/), this was even suggested in the closing comment in the linked issue.

I'm closing this one for now, please feel free to comment/reopen it if you'd like to provide a repro repo.

**Closed by RafikiTiki** 2023-04-17 13:59 UTC
Labels: question

**Comment by sschottler** [comment] 2023-04-18 14:16
Yeah, I did try several newer node versions back when I posted and no luck. Thanks!
