### ISSUE TITLE
Can't find variable: __webpack_require__

### ISSUE THREAD

**Issue by chj-damon** [callstack/repack#275] opened 2022-12-07 13:35 UTC
## Environment

React Native: 0.69.7
Repack: 3.0.0
Webpack: 5.75.0
OS: Windows10 64bit

## Description
I create an demo to learn repack and followed the docs to configure the demo. everything works fine until I configured the `code-splitting` section. It starts to report error like below:

 ERROR  ReferenceError: Can't find variable: __webpack_require__
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
## Reproducible Demo
https://github.com/chj-damon/repackDemo

**Comment by 4tech-david-ho** [comment] 2022-12-12 06:57
meto

**Comment by hikopublic** [comment] 2022-12-13 03:58
Use Node 16

**Comment by 4tech-david-ho** [comment] 2022-12-13 03:58
Use node 16

**Comment by chj-damon** [comment] 2022-12-13 07:03
> 

you mean using node16 can solve this problem?

**Comment by chj-damon** [comment] 2022-12-14 03:35
tried node 16, still fail.

**Comment by RafikiTiki** [comment] 2022-12-22 08:16
@chj-damon I get 404 when trying to visit linked repo

**Comment by chj-damon** [comment] 2022-12-22 08:34
@RafikiTiki sorry about that. I updated the link: https://github.com/chj-damon/repackDemo

**Comment by RafikiTiki** [comment] 2022-12-22 09:11
@chj-damon maybe the repo is private? I'm still getting 404. I'm going to have some time around Wednesday next week to look into repack issues – please send a working repo link by then :)

**Comment by chj-damon** [comment] 2022-12-23 01:53
sorry about that. I've made it public now.

**Comment by namdao** [comment] 2022-12-28 09:46
Me too, I have download repack-sample and disable/enable hermese iOS. And I have still crash when build release mode. But working on debug mode.
**Environment**
React Native: 0.69.7
Repack: 3.0.0
Webpack: 5.75.0
OS: Monterey 
Chip:Apple M1 Pro
![Screen Shot 2022-12-28 at 16 45 36](https://user-images.githubusercontent.com/18393428/209792420-80f66bce-c1ea-4d69-980c-e12bc1253052.png)

**Comment by RafikiTiki** [comment] 2022-12-28 12:51
Hey @chj-damon @namdao I've investigated your problems and I think you both have similar issues – you missed some steps from documentation:

1. Properly configure the app for Release builds: [iOS](https://re-pack.netlify.app/docs/getting-started#4-configure-xcode) and [Android](https://re-pack.netlify.app/docs/getting-started#4-configure-xcode)
2. In the ScriptManager configuration there's a mocked url which you need to configure depending on where you store your remote chunks:

```
  return {
    url: Script.getRemoteURL(`http://somewhere-on-the-internet.com/${scriptId}`)
  };
  ```
  
That piece above needs to be changed to a localhost url if you choose to create a simple http server to serve built chunks or a a cdn if that's what you want.

I'm going to add a disclaimer in the async-chunks guide page to make this more explicit for the people following the guide.

**Comment by chj-damon** [comment] 2022-12-29 01:32
@RafikiTiki Thanks for your reply, but I can confirm that I followed these steps from documentation, I checked my project and `bundleCommand` is correctly configured for sure. you can check the `build.gradle` and `_xcode.env`.

also, the code shows that if it's in dev mode it resolves script to dev server:
```code
ScriptManager.shared.setStorage(AsyncStorage);
ScriptManager.shared.addResolver(async scriptId => {
  // `scriptId` will be either 'student' or 'teacher'
  // In dev mode, resolve script location to dev server.
  if (__DEV__) {
    return {
      url: Script.getDevServerURL(scriptId),
      cache: false,
    };
  }

  return {
    url: Script.getRemoteURL(
      `http://somewhere-on-the-internet.com/${scriptId}`,
    ),
  };
});
```

then it doesn't matter about the remoteURL because this problem is happened in development, not production.

**Comment by chj-damon** [comment] 2022-12-29 01:36
you can also find this code snippet in https://github.com/callstack/repack-examples/blob/main/local-chunks/src/bootstrap.ts

my project code is copied from here: https://re-pack.netlify.app/docs/code-splitting/guide-async-chunks

**Comment by namdao** [comment] 2022-12-29 04:41
Hi [RafikiTiki](https://github.com/RafikiTiki), I have run sample federation module not run async-chunks. And the default simple using below:
```
const resolveURL = Federated.createURLResolver({
  containers: {
    app1: 'http://localhost:9000/[name][ext]',
    app2: 'http://localhost:9001/[name][ext]',
    module1: 'http://localhost:9002/[name][ext]',
  },
});
ScriptManager.shared.addResolver(async (scriptId, caller) => {
  let url;
  if (caller === 'main') {
    url = Script.getDevServerURL(scriptId);
  } else {
    url = resolveURL(scriptId, caller);
  }
  if (!url) {
    return undefined;
  }

  return {
    url,
    cache: false, // For development
    query: {
      platform: Platform.OS,
    },
  };
});
```
And I already run app1,app2,module1 with command "react-native webpack-start"  but still got error when build release mode into host's app.So the host's app run and connect app1,app2,module with localhost is still correct, right?

**Comment by RafikiTiki** [comment] 2022-12-29 10:32
Looks like we're trying to tackle to many problems at the same time.

@namdao Please open a new issue. Since you are using Module Federation instead of async-chunks, the root cause of your problems might be completely different. Please add a repro repo with you code there as well, it helps a lot with investigating these kind of issues. Also, please add info about the platform you're having issues on, the build variant (Release, Debug) and the platform you are working on (Mac, Linux, Windows). From your screenshot it looks like Release iOS, but please add that info so we're on the same page.

@chj-damon I run your `repackDemo` codebase and after:
- adding `bundle-command` to `Bundle React Native code and images` like the docs suggest
- using an url pointing to existing localhost server serving bundles in the ScriptManager config

[Here's the complete diff](https://github.com/chj-damon/repackDemo/compare/master...RafikiTiki:repackDemo:repack/investigation?expand=1). The most important files are `ios/repackDemo.xcodeproj/project.pbxproj` and `index.js`

I was able to build and run:
- the iOS app in both Debug (with devServer) and Release (with localhost server serving `student.chunk.bundle` and `teacher.chunk.bundle`)
- the Android app in Debug variant

Currently I'm not able to run the Android in Release variant, the app crashes instantly after opening. I'm going to investigate it on 9th of January.

Please specify your environment info as well (the platform you're having issues on, the build variant (Release, Debug) and the platform you are working on (Mac, Linux, Windows), thanks!

**Comment by namdao** [comment] 2022-12-29 10:42
Hi @RafikiTiki , I will try investigate detail and open issue later. Thanks for your anwser

**Comment by namdao** [comment] 2023-01-28 05:48
hi @RafikiTiki , sr for reply too late. 
I have missing config on release mode with federation.
Thanks.

**Comment by AkankshaJagdish** [comment] 2023-04-26 09:17
I'm facing a similar issue. Here is the error log:

`2023-04-26 14:30:36.289 30952-31010 AndroidRuntime          com.quiz_app_codesplit_4             E  FATAL EXCEPTION: mqt_native_modules
                                                                                                    Process: com.quiz_app_codesplit_4, PID: 30952
                                                                                                    com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'call' of undefined
                                                                                                    
                                                                                                    This error is located at:
                                                                                                        in Lazy
                                                                                                        in Suspense
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in ImageBackground
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in Home
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in App
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in AppContainer, js engine: hermes, stack:
                                                                                                    __webpack_require__@1:5872
                                                                                                    tryCallOne@53:15
                                                                                                    anonymous@139:26
                                                                                                    anonymous@1:242857
                                                                                                    _callTimer@1:241850
                                                                                                    _callReactNativeMicrotasksPass@1:242018
                                                                                                    callReactNativeMicrotasks@1:243940
                                                                                                    __callReactNativeMicrotasks@1:138053
                                                                                                    anonymous@1:137180
                                                                                                    __guard@1:137930
                                                                                                    flushedQueue@1:137091
`
My webpack config file has been modified to include inline assets:

`
import path from 'path';
import TerserPlugin from 'terser-webpack-plugin';
import * as Repack from '@callstack/repack';

/**
 * More documentation, installation, usage, motivation and differences with Metro is available at:
 * https://github.com/callstack/repack/blob/main/README.md
 *
 * The API documentation for the functions and plugins used in this file is available at:
 * https://re-pack.netlify.app/
 */

/**
 * Webpack configuration.
 * You can also export a static object or a function returning a Promise.
 *
 * @param env Environment options passed from either Webpack CLI or React Native CLI
 *            when running with `react-native start/bundle`.
 */
export default (env) => {
  const {
    mode = 'development',
    context = Repack.getDirname(import.meta.url),
    entry = './index.js',
    platform = process.env.PLATFORM,
    minimize = mode === 'production',
    devServer = undefined,
    bundleFilename = undefined,
    sourceMapFilename = undefined,
    assetsPath = undefined,
    reactNativePath = new URL('./node_modules/react-native', import.meta.url)
      .pathname,
  } = env;
  const dirname = Repack.getDirname(import.meta.url);

  if (!platform) {
    throw new Error('Missing platform');
  }

    /**
   * Using Module Federation might require disabling hmr.
   * Uncomment below to set `devServer.hmr` to `false`.
   *
   * Keep in mind that `devServer` object is not available
   * when running `webpack-bundle` command. Be sure
   * to check its value to avoid accessing undefined value,
   * otherwise an error might occur.
   */
  // if (devServer) {
  //   devServer.hmr = false;
  // }
  
  /**
   * Depending on your Babel configuration you might want to keep it.
   * If you don't use `env` in your Babel config, you can remove it.
   *
   * Keep in mind that if you remove it you should set `BABEL_ENV` or `NODE_ENV`
   * to `development` or `production`. Otherwise your production code might be compiled with
   * in development mode by Babel.
   */
  process.env.BABEL_ENV = mode;

  return {
    mode,
    /**
     * This should be always `false`, since the Source Map configuration is done
     * by `SourceMapDevToolPlugin`.
     */
    devtool: false,
    context,
    /**
     * `getInitializationEntries` will return necessary entries with setup and initialization code.
     * If you don't want to use Hot Module Replacement, set `hmr` option to `false`. By default,
     * HMR will be enabled in development mode.
     */
    entry: [
      ...Repack.getInitializationEntries(reactNativePath, {
        hmr: devServer && devServer.hmr,
      }),
      entry,
    ],
    resolve: {
      /**
       * `getResolveOptions` returns additional resolution configuration for React Native.
       * If it's removed, you won't be able to use `<file>.<platform>.<ext>` (eg: `file.ios.js`)
       * convention and some 3rd-party libraries that specify `react-native` field
       * in their `package.json` might not work correctly.
       */
      ...Repack.getResolveOptions(platform),

      /**
       * Uncomment this to ensure all `react-native*` imports will resolve to the same React Native
       * dependency. You might need it when using workspaces/monorepos or unconventional project
       * structure. For simple/typical project you won't need it.
       */
      // alias: {
      //   'react-native': reactNativePath,
      // },
    },
    /**
     * Configures output.
     * It's recommended to leave it as it is unless you know what you're doing.
     * By default Webpack will emit files into the directory specified under `path`. In order for the
     * React Native app use them when bundling the `.ipa`/`.apk`, they need to be copied over with
     * `Repack.OutputPlugin`, which is configured by default inside `Repack.RepackPlugin`.
     */
    output: {
      clean: true,
      hashFunction: 'xxhash64',
      path: path.join(dirname, 'build/generated', platform),
      filename: 'index.bundle',
      chunkFilename: '[name].chunk.bundle',
      publicPath: Repack.getPublicPath({ platform, devServer }),
    },
    /**
     * Configures optimization of the built bundle.
     */
    optimization: {
      /** Enables minification based on values passed from React Native CLI or from fallback. */
      minimize,
      /** Configure minimizer to process the bundle. */
      minimizer: [
        new TerserPlugin({
          test: /\.(js)?bundle(\?.*)?$/i,
          /**
           * Prevents emitting text file with comments, licenses etc.
           * If you want to gather in-file licenses, feel free to remove this line or configure it
           * differently.
           */
          extractComments: false,
          terserOptions: {
            format: {
              comments: false,
            },
          },
        }),
      ],
      chunkIds: 'named',
    },
    module: {
      /**
       * This rule will process all React Native related dependencies with Babel.
       * If you have a 3rd-party dependency that you need to transpile, you can add it to the
       * `include` list.
       *
       * You can also enable persistent caching with `cacheDirectory` - please refer to:
       * https://github.com/babel/babel-loader#options
       */
      rules: [
        {
          test: /\.[jt]sx?$/,
          include: [
            /node_modules(.*[/\\])+react/,
            /node_modules(.*[/\\])+@react-native/,
            /node_modules(.*[/\\])+@react-navigation/,
            /node_modules(.*[/\\])+@react-native-community/,
            /node_modules(.*[/\\])+@expo/,
            /node_modules(.*[/\\])+pretty-format/,
            /node_modules(.*[/\\])+metro/,
            /node_modules(.*[/\\])+abort-controller/,
            /node_modules(.*[/\\])+@callstack\/repack/,
          ],
          use: 'babel-loader',
        },
        /**
         * Here you can adjust loader that will process your files.
         *
         * You can also enable persistent caching with `cacheDirectory` - please refer to:
         * https://github.com/babel/babel-loader#options
         */
        {
          test: /\.[jt]sx?$/,
          exclude: /node_modules/,
          use: {
            loader: 'babel-loader',
            options: {
              /** Add React Refresh transform only when HMR is enabled. */
              plugins:
                devServer && devServer.hmr
                  ? ['module:react-refresh/babel']
                  : undefined,
            },
          },
        },
        /**
         * This loader handles all static assets (images, video, audio and others), so that you can
         * use (reference) them inside your application.
         *
         * If you wan to handle specific asset type manually, filter out the extension
         * from `ASSET_EXTENSIONS`, for example:
         * ```
         * Repack.ASSET_EXTENSIONS.filter((ext) => ext !== 'svg')
         * ```
         */
        {
          test: Repack.getAssetExtensionsRegExp(Repack.ASSET_EXTENSIONS),
          use: {
            loader: '@callstack/repack/assets-loader',
            options: {
              inline: true, // add the inline option to inline assets as data URIs
              platform,
              devServerEnabled: Boolean(devServer),
              /**
               * Defines which assets are scalable - which assets can have
               * scale suffixes: `@1x`, `@2x` and so on.
               * By default all images are scalable.
               */
              scalableAssetExtensions: Repack.SCALABLE_ASSETS,
            },
          },
        },
      ],
    },
    plugins: [
      /**
       * Configure other required and additional plugins to make the bundle
       * work in React Native and provide good development experience with
       * sensible defaults.
       *
       * `Repack.RepackPlugin` provides some degree of customization, but if you
       * need more control, you can replace `Repack.RepackPlugin` with plugins
       * from `Repack.plugins`.
       */
      new Repack.RepackPlugin({
        context,
        mode,
        platform,
        devServer,
        output: {
          bundleFilename,
          sourceMapFilename,
          assetsPath,
        },
      }),
    ],
  };
};
`


The app uses Firebase to host the chunks. The chunk sizes are about 50 MB - 90 MB. The Scriptmanager resolves the files as follows:

/**
 * @format
 */

// index.js
import { AppRegistry } from 'react-native';
import { ScriptManager, Script } from '@callstack/repack/client';
import AsyncStorage from '@react-native-async-storage/async-storage'; 
import App from './src/App';
import { name as appName } from './app.json';

import firebase from '@react-native-firebase/app';
import storage from '@react-native-firebase/storage'; // import storage module separately
// import { GOOGLE_SERVICES_JSON } from './android/app/google-services.json'; // import Firebase config object
const GOOGLE_SERVICES_JSON = require('./android/app/google-services.json'); // import Firebase config object


// Initialize the Firebase app
if (!firebase.apps.length) {
  firebase.initializeApp(GOOGLE_SERVICES_JSON);
}



ScriptManager.shared.setStorage(AsyncStorage);

// Add resolver to ScriptManager
ScriptManager.shared.addResolver(async (scriptId) => {  
  // In dev mode, resolve script location to local file
  if (__DEV__) {    
    const localFilePath = Script.getDevServerURL(`remotes/${scriptId}.chunk.bundle`);
    console.log('Resolved script URL:', localFilePath);
    return {
      url: localFilePath,
      cache: false,
    };
  }

  // In production mode, resolve script location to Firebase Cloud Storage URL
  const storageRef = storage().ref(`remotes/${scriptId}.chunk.bundle`);
  console.log('Resolved script URL:', storageRef);
  const url1 = await storageRef.getDownloadURL();

  return {
    url: Script.getRemoteURL(url1),
    cache: false,
  };
});

AppRegistry.registerComponent(appName, () => App);


I'm using Ubuntu (WSL) to built the app. I soon will not have access to a Linux device so I must be able to build this using a Windows device with WSL.

I have installed Node, Java, and Adroid SDK on the WSL and am using them to build. 

How do I fix this?

**Comment by RafikiTiki** [comment] 2023-05-24 15:39
@chj-damon For a more complex, real-world example of the Module Federation architecture, please visit the recently released Super App Showcase repo: https://github.com/callstack/super-app-showcase

Closing this issue as it has drifted away from the original problem.

**Closed by RafikiTiki** 2023-05-24 15:39 UTC
Labels: status:investigating, type:question, area:documentation, status:waiting-for-response

**Comment by Kaveh-ap** [comment] 2023-06-03 12:41
@RafikiTiki 
I want to thank you for all the hard work that you've been putting in. 
I've been reading about module federation and tried the "[Step-By-Step Guide to Super App Development](https://www.callstack.com/blog/step-by-step-guide-to-super-app-development)" to get a grasp on this topic. 
However, I'm facing a similar problem after running the project.

Here is my repo: [Example-Repo](https://github.com/Kaveh-ap/RepackExample).

And the warnings that I get are: 
> Property '__webpack_require__' doesn't exist.

> "HostApp" has not been registered...

Is it enough to build the host app and run "yarn start" at the root of the project?
I want to work in the dev environment and mess around with different configs to learn more.

Thanks in advance.

**Comment by jerrynim** [comment] 2023-08-31 02:10
I encountered an issue when using the main.jsbundle file generated with the "react-native bundle" command. I should use the bundle file generated with the "react-native webpack-bundle" command instead.

```
"bundle:ios": "react-native webpack-bundle --platform ios --entry-file index.js  --bundle-output ./ios/main.jsbundle --dev=false"
```

**Comment by jbroma** [comment] 2023-09-01 14:13
> I encountered an issue when using the main.jsbundle file generated with the "react-native bundle" command. I should use the bundle file generated with the "react-native webpack-bundle" command instead.
> 
> ```
> "bundle:ios": "react-native webpack-bundle --platform ios --entry-file index.js  --bundle-output ./ios/main.jsbundle --dev=false"
> ```

`react-native bundle` command uses metro instead of Re.Pack to create the final bundle, so if you used any sort of code-splitting inside of your app it won't work
