### ISSUE TITLE
Not able to run release build

### ISSUE THREAD

**Issue by har2008preet** [callstack/repack#812] opened 2024-12-06 07:36 UTC
### Discussed in https://github.com/callstack/repack/discussions/811

<div type='discussions-op-text'>

<sup>Originally posted by **har2008preet** December  6, 2024</sup>
Hi,

I can create and run my host application which is using modules via ScriptManager, but when i create release build, it is crashing on start with error ReferenceError: Property '__webpack_require__' doesn't exist. I have already included export BUNDLE_COMMAND=webpack-bundle, but i think it is using metro to create release bundle. 

How can i confirm it what it is using to create bundle and how to resolve it? </div>

**Comment by jbroma** [comment] 2024-12-06 08:39
Closing this issue since it's a duplicate of the discussion and this is not following the template

**Closed by jbroma** 2024-12-06 08:39 UTC
