### ISSUE TITLE
Can't resolve './getDevServerLocation'

### ISSUE THREAD

**Issue by DanijelBojcic** [callstack/repack#67] opened 2021-08-13 12:09 UTC
## Environment
```
 webpack 5.50.0,
 @callstack/repack 2.0.0-beta.7,
 iOS: real device iPhone 7,
 react-native:0.64.2
 ```

## Description

I'm trying to implement repack in a monorepo with hermes. 
I have followed the steps in the readme, unfortunately I didn't manage to start the app.
The error I get is :
```
Failed to build bundle due to errors
Error in "../../node_modules/react-native/Libraries/Utilities/HMRClient.js": Module not found: Error: Can't resolve './getDevServerLocation' in 'path_to_root/node_modules/react-native/Libraries/Utilities'
```

My monorepo folder structure looks like this:
```
root/
      packages/
              app1
                     webpack.config.js
              app2
                     webpack.config.js
```

Since I couldn't find any file that requires `./getDevServerLocation`  in `path_to_root/node_modules/react-native/Libraries/Utilities` only in `@callstack/repack/dist/client/runtime`, I guess its a bug or some paths are not set properly.

My webpack.config.js:
```
const path = require("path");
const webpack = require("webpack");
const ReactNative = require("@callstack/repack");
const TerserPlugin = require("terser-webpack-plugin");

const mode = ReactNative.getMode();
const dev = mode === "development";
const context = ReactNative.getContext();
const entry = ReactNative.getEntry();
const platform = ReactNative.getPlatform({ fallback: process.env.PLATFORM });
const minimize = ReactNative.isMinimizeEnabled({ fallback: !dev });
const devServer = ReactNative.getDevServerOptions();
const reactNativePath = ReactNative.getReactNativePath({ fallback: "../../node_modules/react-native" });

const babelConfig = {
  presets: ["module:metro-react-native-babel-preset"],
  plugins: ["react-native-reanimated/plugin"],
  env: {
    production: {
      plugins: [
        "transform-remove-console",
        [
          "babel-plugin-jsx-remove-data-test-id",
          {
            attributes: ["testID", "testId"],
          },
        ],
      ],
    },
  },
};

process.env.BABEL_ENV = mode;

/**
 * Webpack configuration.
 */
module.exports = {
  mode,
  devtool: false,
  context,
  entry: [
    ...ReactNative.getInitializationEntries(reactNativePath, {
      hmr: devServer.hmr,
    }),
    entry,
  ],
  resolve: {
    ...ReactNative.getResolveOptions(platform),
    alias: {
      "react-native": reactNativePath,
    },
  },

  output: {
    clean: true,
    path: path.join(__dirname, "build", platform),
    filename: "index.bundle",
    chunkFilename: "[name].chunk.bundle",
    publicPath: ReactNative.getPublicPath(devServer),
  },

  optimization: {
    minimize,
    minimizer: [
      new TerserPlugin({
        test: /\.(js)?bundle(\?.*)?$/i,
        extractComments: false,
      }),
    ],
  },
  module: {
    rules: [
      {
        test: /\.[jt]sx?$/,
        include: [
          /node_modules(.*[/\\])+react/,
          /node_modules(.*[/\\])+@react-native/,
          /node_modules(.*[/\\])+@react-navigation/,
          /node_modules(.*[/\\])+@react-native-community/,
          /node_modules(.*[/\\])+@expo/,
          /node_modules(.*[/\\])+pretty-format/,
          /node_modules(.*[/\\])+metro/,
          /node_modules(.*[/\\])+abort-controller/,
          /node_modules(.*[/\\])+@callstack[/\\]repack/,
        ],
        use: {
          loader: "babel-loader",
          options: babelConfig,
        },
      },
      {
        test: /\.[jt]sx?$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
          options: {
            ...babelConfig,
            plugins: devServer.hmr ? ["module:react-refresh/babel", ...babelConfig.plugins] : babelConfig.plugins,
          },
        },
      },
    ],
  },
  plugins: [
    new webpack.DefinePlugin({
      __DEV__: JSON.stringify(dev),
    }),
    new ReactNative.AssetsPlugin({
      platform,
      devServerEnabled: devServer.enabled,
    }),
    new ReactNative.TargetPlugin(),
    new ReactNative.OutputPlugin({
      devServerEnabled: devServer.enabled,
    }),
    new ReactNative.DevServerPlugin({
      platform,
      ...devServer,
    }),
    new webpack.SourceMapDevToolPlugin({
      test: /\.(js)?bundle$/,
      exclude: /\.chunk\.(js)?bundle$/,
      filename: "[file].map",
      append: `//# sourceMappingURL=[url]?platform=${platform}`,
    }),
    new webpack.SourceMapDevToolPlugin({
      test: /\.(js)?bundle$/,
      include: /\.chunk\.(js)?bundle$/,
      filename: "[file].map",
      append: `//# sourceMappingURL=[url]?platform=${platform}`,
    }),
    new ReactNative.LoggerPlugin({
      platform,
      devServerEnabled: devServer.enabled,
      output: {
        console: true,
      },
    }),
  ],
};
```

I have also logged out the variables at the top of the config:
```
{
  "mode": "development",
  "dev": true,
  "context": "path_to_root/packages/app1",
  "entry": "./index.js",
  "platform": "ios",
  "minimize": false,
  "devServer": { "enabled": true, "hmr": true, "host": "localhost", "port": 52019 },
  "reactNativePath": "path_to_root/node_modules/react-native"
}
```

**Comment by zamotany** [comment] 2021-08-13 15:37
This is a duplicate of #63 caused by Webpack. For now you have to downgrade to Webpack 5.48.x.

**Closed by zamotany** 2021-08-13 15:37 UTC
