### ISSUE TITLE
ReferenceError: Property'_webpack_require_'

### ISSUE THREAD

**Issue by Tejas281997** [callstack/repack#431] opened 2023-09-26 10:18 UTC
I started the server using yarn start in the root folder, then started mini-app using yarn android, and then used "adb reverse tcp:9000 tcp:9000". Then I tried building a host app using npx react-native run-android in the host-app folder. still getting an error related to webpack require.

Thanks.
<img width="263" alt="Screenshot 2023-09-26 at 3 28 09 PM" src="https://github.com/callstack/repack/assets/125865894/604124d4-a50d-4e1b-b6e2-3addf9114d44">

**Comment by jbroma** [comment] 2023-09-26 10:54
Closing as it's a duplicate of discussion in #429

**Closed by jbroma** 2023-09-26 10:54 UTC
